### ISSUE TITLE
Cannot find the 'cylon-upm-jhd1313m1' module.

### ISSUE THREAD

**Issue by just4give** [hybridgroup/Using-Cylon.js-With-The-Intel-Edison-and-IoT-Starter-Kit#2]
I connected LCD and copied the code in 3.js. When executing , it fails with message 
Cannot find the 'cylon-upm-jhd1313m1' module.

Then I tried to install the npm module but got below error

npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'cylon-upm-jhd1313m1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it

Any one faced this ? Any solution ?

**Comment by deadprogram** [comment]
Hi, @just4give 

Change the driver name from `upm-jhd1313m1` to `jhd1313m1`

Hope that helps!

**Comment by just4give** [comment]
@deadprogram  Thanks for the quick update. Unfortunately that did not solve the problem. It's now complaining 

Cannot find the 'cylon-jhd1313m1' module.

npm install resulted in '404 Not Found' as before. 

I am getting same issue with 'upm-grovetemp'  . Looks like anything upm-\* giving the problem. Am I missing any config or install somewhere ? Any idea ?

**Comment by deadprogram** [comment]
Change `upm-grovetemp` to `temperature-sensor`. 

You also need to make sure you do a `npm install cylon cylon-intel-iot cylon-i2c cylon-gpio` to get to the latest GPIO & I2C drivers.

We will update the code in this repo in the very near future to the latest Cylon.js version.

**Comment by just4give** [comment]
Changing upm-grovetemp to temperature-sensor resolved module not found issue. Now questions is which api to call to get temperature? value() if no more there. Tried with analogRead() but that returned "current temp: null".  

I have all the required module in package.json but still having issue with LED. 

"dependencies": {
    "cylon": "^1.3.0",
    "cylon-gpio": "^0.29.0",
    "cylon-i2c": "^0.26.1",
    "cylon-intel-iot": "^0.12.0",
    "mqtt": "^1.10.0"
  }

**Comment by just4give** [comment]
@deadprogram - I removed node_modules and reinstalled cylon-\* modules. Now LCD Display works perfect with "jhd1313m1" driver. Thanks a lot. 

Can you please let me know which api should I use for temperature sensor ?

**Comment by deadprogram** [comment]
Please take a look at this example: https://github.com/hybridgroup/cylon-gpio/blob/master/examples/temperature/temperature.js

**Comment by just4give** [comment]
@deadprogram you saved my night :) Thanks a lot one more time. Everything works as expected. Hence closing this issue.

**Comment by deadprogram** [comment]
Hi @just4give 

I have a PR here https://github.com/hybridgroup/Using-Cylon.js-With-The-Intel-Edison-and-IoT-Starter-Kit/pull/3 that should include all the needed fixes, in case you want to check it out.
